services:
  ingest:
    build: .
    entrypoint: ["/app/run_pipeline.sh", "ingest"]
    volumes:
      - ./data/raw:/data/raw:ro
      - ./data/warehouse:/data/warehouse

  ingest_synthea:
    build:
      context: .
      dockerfile: ./synthea/Dockerfile
    entrypoint: ["/app/run_pipeline.sh", "ingest_synthea"]
    command: ["200"]
    environment:
      - DUCKDB_PATH=/data/warehouse/mimic_fhir.duckdb
      - SYNTHEA_DATA_PATH=/app/output
    volumes:
      - ./data/warehouse:/data/warehouse
      - ./data/synthea:/app/output

  transform_vitals_eda:
    build: .
    entrypoint: ["/app/run_pipeline.sh", "transform_vitals_eda"]
    volumes:
      - ./data/warehouse:/data/warehouse

  recommendation_pipe:
    build: .
    entrypoint: ["/app/run_pipeline.sh", "recommendation_pipe"]
    environment:
      - DUCKDB_PATH=/data/warehouse/mimic_fhir.duckdb
      - EMBED_MODEL=kamalkraj/BioSimCSE-BioLinkBERT-BASE
      - VECSTORE_PATH=/data/vectorstore
    volumes:
      - ./data/warehouse:/data/warehouse
      - ./data/vectorstore:/data/vectorstore
